import { z } from "zod";

const createAdminValidation = z.object({
  body: z.object({
    adminId: z.string().optional(), // Optional because it may be autogenerated
    name: z.object({
      firstName: z.string().min(1, "First name is required"),
      lastName: z.string().min(1, "Last name is required"),
    }),
    email: z.string().email("Invalid email address"),
    password: z.string().min(6, "Password must be at least 6 characters"),
    phoneNumber: z.string().min(1, "Phone number is required"),
    profilePhotoUrl: z.string().optional(),
  }),
});

const updateAdminValidation = z.object({
  body: z
    .object({
      adminId: z.string().optional(), // Optional because it may be autogenerated
      name: z.object({
        firstName: z.string().optional(),
        lastName: z.string().optional(),
      }),
      email: z.string().email("Invalid email address"),
      password: z.string().min(6, "Password must be at least 6 characters"),
      phoneNumber: z.string().min(1, "Phone number is required"),
      profilePhotoUrl: z.string().optional(),
    })
    .partial(),
});

export const adminValidations = {
  createAdminValidation,
  updateAdminValidation,
};
